name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.2

    - name: Build
      run: |
           go version
           go mod init
           go build -v ./...

    - name: Test
      run: go test -v ./...
